---
.build_serverless_common:
  stage: binary_build
  before_script:
    - !reference [.retrieve_linux_go_deps]
  script:
    - cd cmd/serverless && go build -ldflags="-w -s" -a -v -tags serverless -o $BINARY_NAME

build_serverless-deb_x64:
  extends: .build_serverless_common
  variables:
    BINARY_NAME: datadog-agent-x64
  image: 486234852809.dkr.ecr.us-east-1.amazonaws.com/ci/datadog-agent-buildimages/deb_x64:$DATADOG_AGENT_BUILDIMAGES
  tags: ["runner:main"]
  needs: ["linux_x64_go_deps"]

build_serverless-deb_arm64:
  extends: .build_serverless_common
  variables:
    BINARY_NAME: datadog-agent-arm64
  rules: !reference [.on_all_builds]
  image: 486234852809.dkr.ecr.us-east-1.amazonaws.com/ci/datadog-agent-buildimages/deb_arm64:$DATADOG_AGENT_BUILDIMAGES
  tags: ["runner:docker-arm", "platform:arm64"]
  needs: ["linux_arm64_go_deps"]
